# Generated by Django 4.0.4 on 2022-06-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Contacto')),
                ('nombre_contacto', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
        ),
    ]
