# Generated by Django 4.0.4 on 2022-06-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(default='No ingreso mensaje', verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
    ]
