# Generated by Django 4.0.5 on 2022-06-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contacto_id_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='email',
            new_name='emailContacto',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='id_contacto',
            new_name='idContacto',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='mensaje',
            new_name='mensajeContacto',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='nombre_contacto',
            new_name='nombreContacto',
        ),
    ]
