# Generated by Django 4.0.5 on 2022-07-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_email_contacto_emailcontacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='emailContacto',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='idContacto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensajeContacto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombreContacto',
            field=models.CharField(max_length=50),
        ),
    ]
