# Generated by Django 4.0.5 on 2022-07-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contacto_emailcontacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombremec', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=150)),
                ('mecanico', models.CharField(max_length=150)),
                ('materiales', models.CharField(max_length=150)),
                ('categoria', models.IntegerField(choices=[[0, 'Motor'], [1, 'Frenos'], [2, 'General'], [3, 'Reprogramación electrónica']])),
            ],
        ),
    ]
