# Generated by Django 4.0.5 on 2022-07-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_atencion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='nombremec',
        ),
        migrations.AlterField(
            model_name='atencion',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
    ]
