# Generated by Django 4.0.5 on 2022-07-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_atencion_nombremec_alter_atencion_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atencion',
            new_name='Servicio',
        ),
    ]
